### PR TITLE
fix(parser): handle case with LTChar directly under page

### PR DESCRIPTION
**Pull request by matchaxnb**
Some characters are directly under a LTPage and this makes the parser crash when using pdfminer.six==20231228 as LTChar are not iterable.

(tested with the Jupiter XM MIDI spec ref file with prefix `eng06_W.pdf`)

### CODE REVIEW

**Comment by matchaxnb** [comment]
Add useful feature to convert jupx.json to YAML for better readability (with hex addresses)

**Comment by asutherland** [comment]
Thank you for the fixes!  It's very exciting that someone else found this effort interesting enough to get it working on new doc breakage!

I'm hoping to get back to hacking in this space again in the future, in particular in using hardware controllers and displays to make ZenCore devices effectively more knob-per-function.  If you're doing something in this space, I'd be very interested to hear about it / be linked to it!

**Comment by matchaxnb** [comment]
Hey Andrew,

I completed the order and I'm building a memory explorer for the synth I'll push it today it's imperfect and slow but it works. My goal is to make a custom controller to touch sysex stuff directly or as macros (doing the hardware bridge part with a feather from adafruit)

**Comment by asutherland** [comment]
> I completed the order and I'm building a memory explorer for the synth I'll push it today it's imperfect and slow but it works. My goal is to make a custom controller to touch sysex stuff directly or as macros (doing the hardware bridge part with a feather from adafruit)

I just checked out https://github.com/matchalunatic/jupiter-xm-midi-controller.git and it looks super cool!  Thanks for commenting back here!  I have a Keystep Pro to go with my Jupiter XM, so I definitely will be interested to follow where that goes!  (I don't have any AdaFruit feathers, but presumably I could use something else to help with the MIDI hookup, like maybe I can route things through a Conductive Labs MRCC that's connected to the software running on a USB host.)

**Pull request merged**
